[greeter]
background=/usr/share/pixmaps/tunebian-login-background.svg
logo=/usr/share/pixmaps/install-tunebian.svg
theme-name=Adwaita
icon-theme-name=Tango
font-name=Sans 10
xft-antialias=true
xft-hintstyle=hintfull
xft-rgba=rgb
