---
dontChroot: false
script:
  - "rm -f /etc/sudoers.d/99-tunebian-live-installer"
  - "rm -f /usr/bin/calamares-install-tunebian"
  - "rm -f /usr/bin/add-calamares-desktop-icon"
  - "rm -f /usr/share/applications/calamares-install-tunebian.desktop"
  - "rm -f /usr/share/applications/calamares-install-debian.desktop"
  - "rm -f /etc/xdg/autostart/calamares-desktop-icon.desktop"
  - "rm -f /usr/share/pixmaps/install-tunebian.svg"
