---
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false

requirements:
    requiredStorage: 15
    requiredRam: 1.0
    check:
        - storage
        - ram
        - root
    required:
        - storage
        - ram
        - root
